package com.fillumina.xjc.validation;

import com.sun.codemodel.JFieldVar;
import com.sun.tools.xjc.model.CAttributePropertyInfo;
import com.sun.tools.xjc.model.CElementPropertyInfo;
import com.sun.tools.xjc.model.CPropertyInfo;
import com.sun.tools.xjc.model.CValuePropertyInfo;
import com.sun.tools.xjc.outline.ClassOutline;
import com.sun.tools.xjc.outline.Outline;
import com.sun.xml.xsom.XSComponent;
import com.sun.xml.xsom.XSParticle;
import com.sun.xml.xsom.XSSimpleType;
import com.sun.xml.xsom.XSTerm;
import com.sun.xml.xsom.XSType;
import com.sun.xml.xsom.XmlString;
import com.sun.xml.xsom.impl.AttributeUseImpl;
import com.sun.xml.xsom.impl.ElementDecl;
import com.sun.xml.xsom.impl.ModelGroupImpl;
import com.sun.xml.xsom.impl.SimpleTypeImpl;
import java.lang.annotation.Annotation;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Performs the actual job of creating the annotations. The classes are generated by XJC.
 *
 * @author Francesco Illuminati
 */
class Processor {

    private final BeanValidationOptions options;
    private final OverrideStatements overrides;

    Processor(BeanValidationOptions options) {
        this.options = options;
        this.overrides = OverrideStatements.of(options.getOverrides());
    }

    /** Walks the generated classes and writes the annotations of their properties. */
    void process(Outline outline) {
        for (ClassOutline classOutline : outline.getClasses()) {
            // the statements match the qualified name: a glob can then cover a package
            String className = classOutline.implClass.fullName();

            // the properties for each class
            List<CPropertyInfo> properties = classOutline.target.getProperties();

            for (CPropertyInfo property : properties) {

                String propertyName = property.getName(false);

                AnnotationLog logger = options.isVerbose()
                        ? new AnnotationLogAll(className, propertyName)
                        : AnnotationLogWarning.INSTANCE;

                // a property with a statement is processed as usual, but its annotations are collected
                // instead of written, so that a replacement can use the values they would have had
                List<OverrideStatements.Statement> overridesForProperty =
                        overrides.statementsFor(className, propertyName);
                List<AnnotationWriter.Annotate> collected = overridesForProperty.isEmpty()
                        ? null : new ArrayList<AnnotationWriter.Annotate>();

                new PropertyProcessor(classOutline, logger, collected).processProperty(property);

                if (collected != null) {
                    JFieldVar field = classOutline.implClass.fields().get(propertyName);
                    if (field != null) {
                        writeOverrided(field, className, propertyName, collected,
                                overridesForProperty, logger);
                    }
                }
            }
        }

        reportUnmatchedExclusions();
    }

    /**
     * Writes what the statements leave behind: the computed annotations none of them covers, the ones
     * a statement gave a parameter, and the replacement of every statement that carries one.
     */
    private void writeOverrided(JFieldVar field, String className, String propertyName,
            List<AnnotationWriter.Annotate> collected, List<OverrideStatements.Statement> statements,
            AnnotationLog logger) {
        AnnotationWriter fieldWriter = new AnnotationWriter(field, logger);
        // the annotations of the items go back on the type argument, so they are kept apart here
        ItemAnnotator items = new ItemAnnotator(field, logger, null);
        Set<OverrideStatements.Statement> replacingOnTheField = new LinkedHashSet<>();
        Set<OverrideStatements.Statement> replacingOnTheItems = new LinkedHashSet<>();
        boolean itemWritten = false;
        // a placeholder reads the annotations the statement selects, not every annotation of the property
        Map<OverrideStatements.Statement, List<AnnotationWriter.Annotate>> covered = new LinkedHashMap<>();
        for (OverrideStatements.Statement statement : statements) {
            covered.put(statement, coveredBy(collected, statement));
        }
        for (AnnotationWriter.Annotate computed : collected) {
            Map<String, String> parameters = new LinkedHashMap<>();
            boolean leftOut = false;
            for (OverrideStatements.Statement statement : statements) {
                if (!statement.coversAnnotation(computed.getAnnotationClass().getSimpleName(),
                        computed.isTypeArgument())) {
                    continue;
                }
                if (statement.hasReplacement()) {
                    (computed.isTypeArgument() ? replacingOnTheItems : replacingOnTheField)
                            .add(statement);
                    leftOut = true;
                } else if (statement.hasParameter()) {
                    parameters.put(statement.getParameter(), OverrideReplacement.resolveValue(
                            statement.getParameterValue(), computed.getAnnotationClass(), className,
                            propertyName, covered.get(statement)));
                } else {
                    leftOut = true;
                }
            }
            if (!leftOut) {
                OverrideReplacement.writeComputed(
                        computed.isTypeArgument() ? items.writer() : fieldWriter, computed,
                        parameters, logger);
                itemWritten |= computed.isTypeArgument();
            }
        }
        for (OverrideStatements.Statement statement : statements) {
            boolean onTheField = replacingOnTheField.contains(statement);
            boolean onTheItems = replacingOnTheItems.contains(statement);
            if (onTheField || onTheItems) {
                OverrideReplacement replacement = OverrideReplacement.parse(statement.getReplacement());
                if (onTheField) {
                    replacement.writeInto(fieldWriter, className, propertyName, covered.get(statement), logger);
                }
                if (onTheItems) {
                    replacement.writeInto(items.writer(), className, propertyName, covered.get(statement), logger);
                    itemWritten = true;
                }
            }
        }
        if (itemWritten) {
            items.apply();
        }
    }

    /** @return the annotations the statement selects, which are the ones its placeholders read. */
    private static List<AnnotationWriter.Annotate> coveredBy(List<AnnotationWriter.Annotate> computed,
            OverrideStatements.Statement statement) {
        List<AnnotationWriter.Annotate> covered = new ArrayList<>();
        for (AnnotationWriter.Annotate annotation : computed) {
            if (statement.coversAnnotation(annotation.getAnnotationClass().getSimpleName(),
                    annotation.isTypeArgument())) {
                covered.add(annotation);
            }
        }
        return covered;
    }

    /** A statement that matched nothing is a typo, and it silently leaves the annotations in place. */
    private void reportUnmatchedExclusions() {
        AnnotationLog logger = options.isVerbose()
                ? new AnnotationLogAll("", "")
                : AnnotationLogWarning.INSTANCE;
        for (OverrideStatements.Statement statement : overrides.unmatched()) {
            logger.warning("override=" + statement + " matched no class, property or annotation");
        }
    }

    class PropertyProcessor {

        private final AnnotationLog logger;
        private final ClassOutline classOutline;
        private final List<AnnotationWriter.Annotate> collector;

        PropertyProcessor(ClassOutline classOutline, AnnotationLog logger,
                List<AnnotationWriter.Annotate> collector) {
            this.logger = logger;
            this.classOutline = classOutline;
            this.collector = collector;
        }

        void processProperty(CPropertyInfo property) {
            if (property instanceof CElementPropertyInfo) {
                processElement((CElementPropertyInfo) property);

            } else if (property instanceof CAttributePropertyInfo) {
                processAttribute((CAttributePropertyInfo) property);

            } else if (property instanceof CValuePropertyInfo) {
                processAttribute((CValuePropertyInfo) property);
            }
        }

        /**
         * parses xsd:element
         */
        private void processElement(CElementPropertyInfo property) {
            String propertyName = property.getName(false);

            // Not an error: XJC leaves the component null when the model is built from something
            // other than XML Schema (a DTD, say) and passes the element declaration for the element
            // class of a simple content. Nothing can be annotated then, so the element is ignored, as
            // the attribute path does for a property without a field.
            XSComponent definition = property.getSchemaComponent();
            if (!(definition instanceof XSParticle)) {
                return;
            }
            XSParticle particle = (XSParticle) definition;
            XSTerm term = particle.getTerm();
            final JFieldVar field = classOutline.implClass.fields().get(propertyName);
            if (field == null) {
                return;
            }
            FieldAnnotator annotator = new FieldAnnotator(field, logger, collector);

            if (term instanceof ModelGroupImpl) {
                processModelGroupIml(property, annotator);
            } else if (term instanceof ElementDecl) {
                processElementDecl(property, field, particle, (ElementDecl) term, annotator);
            }
            annotator.applyItemAnnotations();
        }

        /**
         * A model group becomes a field of {@code List<Object>}, another container, so it follows
         * the option the element collections follow and carries its {@code @Valid} on the type
         * argument.
         */
        private void processModelGroupIml(CElementPropertyInfo property, FieldAnnotator annotator) {
            if (options.isGenerateValidOnCollections()) {
                annotator.items().addValidAnnotation();
            }
        }

        /**
         * parses xsd:element
         */
        private void processElementDecl(
                CElementPropertyInfo property,
                JFieldVar field,
                XSParticle particle,
                ElementDecl element,
                FieldAnnotator annotator) {

            final int minOccurs = particle.getMinOccurs().intValue();
            final int maxOccurs = particle.getMaxOccurs().intValue();
            final boolean required = property.isRequired() || property.isCollectionRequired();
            final boolean nillable = element.isNillable() || property.isCollectionNillable();
            final String targetNamespace = element.getOwnerSchema().getTargetNamespace();

            final XSType elementType = element.getType();
            final boolean isComplexType = elementType.isComplexType();
            final FieldHelper fieldHelper = new FieldHelper(field);

            // minOccurs > 0 and required == false means the attribute is part of a <xsd:choice>
            // and @NotNull should not be added so only required qualifies to add @NotNull
            if (options.isNotNullAnnotations() && !nillable && required) {
                String message = notNullMessage(classOutline, field);
                annotator.addNotNullAnnotation(message);
            }

            // a boolean the schema pins to one value: the annotation says which, and considers a null
            // valid, so an optional element needs nothing else
            if (!property.isCollection() && fieldHelper.isBoolean()) {
                addFixedBooleanAnnotation(annotator, element.getFixedValue());
            }

            // the cardinality of a collection: minOccurs = 0 is the default and constrains
            // nothing, so it is not written, and an unbounded maxOccurs arrives as -1 and is left
            // out by the annotator
            if (property.isCollection() && (minOccurs != 1 || maxOccurs != 1)) {
                annotator.addSizeAnnotation(minOccurs == 0 ? null : minOccurs, maxOccurs, null);
            }

            final boolean inTargetNamespace =
                    TargetNamespace.accepts(options.getTargetNamespace(), targetNamespace);
            // the @Valid of a container goes on the type argument, where a current provider reads
            // it; any other complex type carries it on the field whatever the option says
            if (inTargetNamespace) {
                if (property.isCollection()) {
                    // cascading makes sense on the elements of a complex type: on a list of strings
                    // or of an enumeration it would validate nothing
                    if (options.isGenerateValidOnCollections() && isComplexType) {
                        annotator.items().addValidAnnotation();
                    }
                } else if (isComplexType) {
                    annotator.addValidAnnotation();
                }
            }

            final XSSimpleType simpleType;
            if (isComplexType) {
                simpleType = elementType.getBaseType().asSimpleType();
            } else {
                simpleType = elementType.asSimpleType();
            }

            if (simpleType != null) {

                // a complex type can contribute the facet of only one of its possibilities; the
                // items of a collection are annotated on its type argument
                FacetSourceAccumulator facet = FacetGatherer.gather(simpleType);
                if (property.isCollection()) {

                    if (options.isItemAnnotations()) {
                        FacetSourceAccumulator itemFacet = facet.itemFacet();
                        if (itemFacet != null) {
                            // the field is a list because its type is an xsd:list, so the length
                            // facets gathered here count the items in it and belong on the field
                            annotator.addSizeAnnotation(facet.minLength(), facet.maxLength(),
                                    facet.length());
                            setItemAnnotations(fieldHelper, annotator.items(), itemFacet);
                        } else {
                            // an element that inherits occurrences other than one is promoted to a
                            // list, so the facet already refers to the item
                            if (!fieldHelper.isList()) {
                                throw new IllegalStateException("the facets of "
                                        + property.getName(false) + " cannot be written on its type"
                                        + " argument: report this together with the schema that"
                                        + " provoked it");
                            }
                            setItemAnnotations(fieldHelper, annotator.items(), facet);
                        }
                    }

                } else {

                    BigDecimal fixedBound = fixedBoundOf(fieldHelper, element.getFixedValue());
                    if (fixedBound != null) {
                        facet.setFixedValue(fixedBound);
                    }
                    processType(fieldHelper, annotator, facet);

                }

            }
        }

        /** The constraints of the items of a collection: they end up on its type argument. */
        private void setItemAnnotations(FieldHelper fieldHelper, ItemAnnotator items, FacetSourceAccumulator facet) {
            items.addSizeAnnotation(facet.minLength(), facet.maxLength());
            items.addDigitsAnnotation(facet.totalDigits(), facet.fractionDigits());
            items.addDecimalMinAnnotation(
                    itemBound(fieldHelper, facet.minInclusive()),
                    itemBound(fieldHelper, facet.minExclusive()));
            items.addDecimalMaxAnnotation(
                    itemBound(fieldHelper, facet.maxInclusive()),
                    itemBound(fieldHelper, facet.maxExclusive()));
            // @Pattern resolves to a validator that accepts CharSequence only: on a collection of
            // numbers it would check nothing and fail at validation time
            if (fieldHelper.isStringList()) {
                items.addPatterns(facet.translatedMultiPatterns(logger), options.isPatternList());
            }
        }

        /**
         * @return the bound as it is written, unless the option leaves out the ones the Java type
         *     already states
         */
        private BigDecimal itemBound(FieldHelper fieldHelper, BigDecimal bound) {
            return options.isOmitJavaTypeBounds() ? fieldHelper.itemBound(bound) : bound;
        }

        /**
         * Writes {@code @AssertTrue} or {@code @AssertFalse} for a boolean pinned by {@code fixed},
         * which XML Schema spells {@code true}, {@code false}, {@code 1} or {@code 0}.
         */
        private void addFixedBooleanAnnotation(FieldAnnotator annotator, XmlString fixedValue) {
            if (fixedValue == null) {
                return;
            }
            if ("true".equals(fixedValue.value) || "1".equals(fixedValue.value)) {
                annotator.addAssertTrueAnnotation();
            } else if ("false".equals(fixedValue.value) || "0".equals(fixedValue.value)) {
                annotator.addAssertFalseAnnotation();
            }
        }

        /**
         * parses xsd:attribute
         */
        private void processAttribute(CAttributePropertyInfo property) {
            String propertyName = property.getName(false);

            XSComponent definition = property.getSchemaComponent();
            if (definition instanceof AttributeUseImpl) {
                AttributeUseImpl particle = (AttributeUseImpl) definition;
                XSSimpleType type = particle.getDecl().getType();

                JFieldVar field = classOutline.implClass.fields().get(propertyName);

                if (field != null) {
                    FieldAnnotator annotator =
                            new FieldAnnotator(field, logger, collector);

                    if (options.isNotNullAnnotations() && particle.isRequired()) {
                        String message = notNullMessage(classOutline, field);
                        annotator.addNotNullAnnotation(message);
                    }

                    FieldHelper fieldHelper = new FieldHelper(field);
                    if (fieldHelper.isBoolean()) {
                        addFixedBooleanAnnotation(annotator, particle.getDecl().getFixedValue());
                    }
                    FacetSourceAccumulator facet = FacetGatherer.gather(type);
                    BigDecimal fixedBound =
                            fixedBoundOf(fieldHelper, particle.getDecl().getFixedValue());
                    if (fixedBound != null) {
                        facet.setFixedValue(fixedBound);
                    }
                    processType(fieldHelper, annotator, facet);
                }
            }
        }

        /**
         * The value pinned by {@code fixed}, as a bound, or null when there is none or the field
         * cannot carry a numeric bound: a decimal bound on a string field would mean nothing.
         */
        private BigDecimal fixedBoundOf(FieldHelper fieldHelper, XmlString fixedValue) {
            if (fixedValue == null || !fieldHelper.isNumber()) {
                return null;
            }
            return new BigDecimal(fixedValue.value);
        }

        /**
         * parses values
         *
         * NOTE: needed to process complexTypes extending a simpleType
         */
        private void processAttribute(CValuePropertyInfo property) {
            String propertyName = property.getName(false);

            XSComponent definition = property.getSchemaComponent();
            if (definition instanceof SimpleTypeImpl) {
                SimpleTypeImpl particle = (SimpleTypeImpl) definition;
                XSSimpleType simpleType = particle.asSimpleType();

                JFieldVar field = classOutline.implClass.fields().get(propertyName);

                if (field != null) {
                    FieldAnnotator annotator =
                            new FieldAnnotator(field, logger, collector);

                    processType(simpleType, field, annotator);
                }
            }
        }

        private void processType(XSSimpleType simpleType, JFieldVar field, FieldAnnotator annotator) {
            FacetSourceAccumulator facet = FacetGatherer.gather(simpleType);
            FieldHelper fieldHelper = new FieldHelper(field);
            processType(fieldHelper, annotator, facet);
        }

        /**
         * Process types which are not collections
         */
        private void processType(
                FieldHelper fieldHelper,
                FieldAnnotator annotator,
                FacetSourceAccumulator facet) {

            if (fieldHelper.isArray() || fieldHelper.isString()) {
                annotator.addSizeAnnotation(facet.minLength(), facet.maxLength(), facet.length());
            }

            if (fieldHelper.isString()) {
                annotator.addPatterns(facet.multiPatterns(), options.isPatternList());
            }

            if (fieldHelper.isNumber() || fieldHelper.isString()) {
                if (options.isOmitJavaTypeBounds()) {
                    annotator.addDecimalMinAnnotationInclusive(fieldHelper.fieldBound(facet.minInclusive()));
                    annotator.addDecimalMinAnnotationExclusive(fieldHelper.fieldBound(facet.minExclusive()));
                    annotator.addDecimalMaxAnnotationInclusive(fieldHelper.fieldBound(facet.maxInclusive()));
                    annotator.addDecimalMaxAnnotationExclusive(fieldHelper.fieldBound(facet.maxExclusive()));

                } else {
                    annotator.addDecimalMinAnnotationInclusive(facet.minInclusive());
                    annotator.addDecimalMinAnnotationExclusive(facet.minExclusive());
                    annotator.addDecimalMaxAnnotationInclusive(facet.maxInclusive());
                    annotator.addDecimalMaxAnnotationExclusive(facet.maxExclusive());
                }
                annotator.addDigitsAnnotation(facet.totalDigits(), facet.fractionDigits());
            }

        }
    }


    String notNullMessage(ClassOutline classOutline, JFieldVar field) {
        final String className = classOutline.implClass.name();
        final Class<? extends Annotation> notNullClass = ValidationAnnotations.NOT_NULL;

        String message = null;

        if (options.isNotNullPrefixClassName()) {
            message = String.format("%s.%s {%s.message}",
                    className, field.name(),
                    notNullClass.getName());

        } else if (options.isNotNullPrefixFieldName()) {
            message = String.format("%s {%s.message}",
                    field.name(),
                    notNullClass.getName());

        } else if (options.isNotNullCustomMessage()) {
            message = String.format("{%s.message}",
                    notNullClass.getName());

        } else if (options.getNotNullCustomMessageText() != null) {
            message = options.getNotNullCustomMessageText()
                    .replace("{ClassName}", className)
                    .replace("{FieldName}", field.name());
        }

        return message;
    }

}
